default_language_version:
  python: python3
repos:
  - repo: https://github.com/psf/black.git
    rev: 22.8.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8.git
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ["-ll"]
        files: .py$
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
